version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"   
    container_name: mongodb   
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"     
    container_name: rabbitmq            
  product:
    build:
      dockerfile: Dockerfile
      context: ./product
    container_name: product
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - rabbitmq    
      - mongodb
    volumes:
      - .:/app
      - /app/product/node_modules
    env_file:
      - ./product/.env      
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    volumes:
      - .:/app
      - /app/shopping/node_modules
    depends_on:
      - rabbitmq    
      - mongodb       
    env_file:
      - ./shopping/.env      
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app/
      - /app/customer/node_modules
    depends_on:
      - rabbitmq    
      - mongodb         
    env_file:
      - ./customer/.env    
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - product
      - shopping
      - customer
    ports:
      - 80:80